<form id="login" action="<?php $this->element->getAction(); ?>" method="<? echo $this->element->getMethod(); ?>">
    <p>Project Name</p>
    <?php echo $this->element->ProjectName; ?>
    <br/>
    <p>Description</p>
    <?php echo $this->element->Description; ?>
    <br/>
    <p>Catagorie</p>
    <?php echo $this->element->Categorie; ?>
    <br/>
    <?php echo $this->element->submit; ?>
</form>
