<div class="body"></div>
<div class="grad"></div>
<div class="header">
    <div>Project<span>Manager</span></div>
</div>
<br>
<div class="login">
<form id="login" action="<?php $this->element->getAction(); ?>" method="<? echo $this->element->getMethod(); ?>">
    <?php echo $this->element->email; ?>
    <br/>
    <?php echo $this->element->pswd; ?>
    <br/>
    <?php echo $this->element->submit; ?>
</form>

</div>

<script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>