<html>
<head>
    <title>Project Manager</title>
    <link rel="stylesheet" href="/css/dashboard.css" type="text/css" media="screen, projection">

</head>
<body>

<header class="project subhead">

    <div class="container container-narrow">
        <h1>Project Manager Dashboard </h1>
    </div>

    <p>Welcome; <?php echo $this->id;?></p>
    <a href="<?= $this->url(array(
        'controller' => 'Login',
        'action' => 'Logout')); ?>">Logout</a>

    <?php if (count($this->messages) > 0) { printf("<div id='flash'>%s</div>", $this->messages[0]);} ?>

</header>

    <div class="container">
    <?php echo $this->layout()->content; ?>
    </div>


<footer class="footer">
    <div class="container container-narrow">
    <p>Project Manager V.0.1 </p> <p>Support mail <?php echo $this->supportEmail;?></p></div>
</footer>

</body>
</html>

